---
- name: Create Consul service definition
  tags: ['role::tinc', 'role::tinc:consul']
  template:
    src: service_tinc.json
    dest: '{{ tinc_consul_service_path }}'
  notify:
    - reload consul
