---
# Enable connections from the Tinc VPN `tun0` interface
- name: Enable VPN connections
  tags: ['role::tinc', 'role::tinc:firewall']
  iptables:
    comment: VPN connections
    chain: INPUT
    jump: ACCEPT
    in_interface: tun0

- name: Check if Docker is present
  stat:
    path: '/etc/docker/daemon.json'
  register: docker_config

- name: Enable VPN connections for Docker
  tags: ['role::tinc', 'role::tinc:firewall']
  iptables:
    chain: DOCKER-USER
    action: insert
    comment: VPN connections
    in_interface: tun0
    jump: ACCEPT
  when: docker_config.stat.exists

- name: Enable various service ports
  tags: ['role::tinc', 'role::tinc:firewall']
  iptables:
    chain: INPUT
    jump: ACCEPT
    source: '0.0.0.0/0'
    comment: '{{ item.cmt }}'
    protocol: '{{ item.prot | default("tcp") }}'
    destination_port: '{{ item.port }}'
  with_items:
    - { "port": 655,  "cmt": "Tinc VPN TCP" }
    - { "port": 655,  "cmt": "Tinc VPN UDP", "prot": "udp" }

- name: Save iptables rules
  shell: iptables-save > /etc/iptables/rules.v4
