---
- name: Install tinc VPN
  tags: ['role::tinc', 'role::tinc:install']
  apt:
    pkg: tinc

- name: Create the hosts dir
  tags: ['role::tinc', 'role::tinc:install']
  file:
    path: '{{ tinc_network_path }}/hosts'
    state: directory

- name: Define default network
  tags: ['role::tinc', 'role::tinc:install']
  lineinfile:
    path: /etc/tinc/nets.boot
    regexp: '^{{ tinc_network_name }}$'
    line: '{{ tinc_network_name }}'
    state: present

- name: Install python dependencies
  tags: ['role::tinc', 'role::tinc:install']
  pip:
    name:
      - python-hosts
      - python-consul
    executable: pip3

- name: Copy up, down, & refresh scritps
  tags: ['role::tinc', 'role::tinc:install']
  copy:
    src: '{{ item }}'
    dest: '{{ tinc_network_path }}/{{ item }}'
    mode: 0750
  with_items:
    - tinc-up
    - tinc-down
    - tinc-refresh
