---
- include_tasks: install.yml
  tags: ['role::bootstrap:tinc']
- include_tasks: config.yml
  tags: ['role::bootstrap:tinc']
- include_tasks: health.yml
  tags: ['role::bootstrap:tinc']
- include_tasks: consul.yml
  tags: ['role::bootstrap:tinc']
- include_tasks: firewall.yml
  tags: ['role::bootstrap:tinc']

- name: Set Tinc IP as Ansible fact
  tags: ['role::bootstrap:tinc']
  set_fact:
    ansible_local:
      tinc:
        vpn_ip: '{{ tinc_ip_file.content | b64decode }}'
