---
- include_tasks: install.yml
  tags: ['role::tinc', 'role::tinc:install']
- include_tasks: config.yml
  tags: ['role::tinc', 'role::tinc:config']
- include_tasks: service.yml
  tags: ['role::tinc', 'role::tinc:service']
- include_tasks: health.yml
  tags: ['role::tinc', 'role::tinc:health']
- include_tasks: consul.yml
  tags: ['role::tinc', 'role::tinc:consul']
- include_tasks: firewall.yml
  tags: ['role::tinc', 'role::tinc:firewall']

- name: Set Tinc IP as Ansible fact
  tags: ['role::tinc', 'role::tinc:fact']
  set_fact:
    ansible_local:
      tinc:
        vpn_ip: '{{ tinc_ip_file.content | b64decode }}'
